//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:cloudflare_dart/src/model/realtimekit_participant.dart';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'add_participant201_response_all_of_data.g.dart';

/// AddParticipant201ResponseAllOfData
///
/// Properties:
/// * [createdAt] - When this object was created. The time is returned in ISO format.
/// * [customParticipantId] - A unique participant ID generated by the client.
/// * [id] - ID of the participant.
/// * [name] - Name of the participant.
/// * [picture] - URL to a picture of the participant.
/// * [presetName] - Preset applied to the participant.
/// * [updatedAt] - When this object was updated. The time is returned in ISO format.
/// * [token] - The participant's auth token that can be used for joining a meeting from the client side.
@BuiltValue()
abstract class AddParticipant201ResponseAllOfData implements RealtimekitParticipant, Built<AddParticipant201ResponseAllOfData, AddParticipant201ResponseAllOfDataBuilder> {
  /// The participant's auth token that can be used for joining a meeting from the client side.
  @BuiltValueField(wireName: r'token')
  String get token;

  AddParticipant201ResponseAllOfData._();

  factory AddParticipant201ResponseAllOfData([void updates(AddParticipant201ResponseAllOfDataBuilder b)]) = _$AddParticipant201ResponseAllOfData;

  @BuiltValueHook(initializeBuilder: true)
  static void _defaults(AddParticipant201ResponseAllOfDataBuilder b) => b;

  @BuiltValueSerializer(custom: true)
  static Serializer<AddParticipant201ResponseAllOfData> get serializer => _$AddParticipant201ResponseAllOfDataSerializer();
}

class _$AddParticipant201ResponseAllOfDataSerializer implements PrimitiveSerializer<AddParticipant201ResponseAllOfData> {
  @override
  final Iterable<Type> types = const [AddParticipant201ResponseAllOfData, _$AddParticipant201ResponseAllOfData];

  @override
  final String wireName = r'AddParticipant201ResponseAllOfData';

  Iterable<Object?> _serializeProperties(
    Serializers serializers,
    AddParticipant201ResponseAllOfData object, {
    FullType specifiedType = FullType.unspecified,
  }) sync* {
    yield r'created_at';
    yield serializers.serialize(
      object.createdAt,
      specifiedType: const FullType(DateTime),
    );
    yield r'preset_name';
    yield serializers.serialize(
      object.presetName,
      specifiedType: const FullType(String),
    );
    if (object.name != null) {
      yield r'name';
      yield serializers.serialize(
        object.name,
        specifiedType: const FullType.nullable(String),
      );
    }
    yield r'custom_participant_id';
    yield serializers.serialize(
      object.customParticipantId,
      specifiedType: const FullType(String),
    );
    yield r'id';
    yield serializers.serialize(
      object.id,
      specifiedType: const FullType(String),
    );
    if (object.picture != null) {
      yield r'picture';
      yield serializers.serialize(
        object.picture,
        specifiedType: const FullType.nullable(String),
      );
    }
    yield r'token';
    yield serializers.serialize(
      object.token,
      specifiedType: const FullType(String),
    );
    yield r'updated_at';
    yield serializers.serialize(
      object.updatedAt,
      specifiedType: const FullType(DateTime),
    );
  }

  @override
  Object serialize(
    Serializers serializers,
    AddParticipant201ResponseAllOfData object, {
    FullType specifiedType = FullType.unspecified,
  }) {
    return _serializeProperties(serializers, object, specifiedType: specifiedType).toList();
  }

  void _deserializeProperties(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
    required List<Object?> serializedList,
    required AddParticipant201ResponseAllOfDataBuilder result,
    required List<Object?> unhandled,
  }) {
    for (var i = 0; i < serializedList.length; i += 2) {
      final key = serializedList[i] as String;
      final value = serializedList[i + 1];
      switch (key) {
        case r'created_at':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(DateTime),
          ) as DateTime;
          result.createdAt = valueDes;
          break;
        case r'preset_name':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(String),
          ) as String;
          result.presetName = valueDes;
          break;
        case r'name':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.name = valueDes;
          break;
        case r'custom_participant_id':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(String),
          ) as String;
          result.customParticipantId = valueDes;
          break;
        case r'id':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(String),
          ) as String;
          result.id = valueDes;
          break;
        case r'picture':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.picture = valueDes;
          break;
        case r'token':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(String),
          ) as String;
          result.token = valueDes;
          break;
        case r'updated_at':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(DateTime),
          ) as DateTime;
          result.updatedAt = valueDes;
          break;
        default:
          unhandled.add(key);
          unhandled.add(value);
          break;
      }
    }
  }

  @override
  AddParticipant201ResponseAllOfData deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final result = AddParticipant201ResponseAllOfDataBuilder();
    final serializedList = (serialized as Iterable<Object?>).toList();
    final unhandled = <Object?>[];
    _deserializeProperties(
      serializers,
      serialized,
      specifiedType: specifiedType,
      serializedList: serializedList,
      unhandled: unhandled,
      result: result,
    );
    return result.build();
  }
}

