//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'delete_meeting_participant200_response_all_of_data.g.dart';

/// DeleteMeetingParticipant200ResponseAllOfData
///
/// Properties:
/// * [createdAt] - Timestamp this object was created at. The time is returned in ISO format.
/// * [customParticipantId] - A unique participant ID generated by the client.
/// * [presetId] - ID of the preset applied to this participant.
/// * [updatedAt] - Timestamp this object was updated at. The time is returned in ISO format.
@BuiltValue()
abstract class DeleteMeetingParticipant200ResponseAllOfData implements Built<DeleteMeetingParticipant200ResponseAllOfData, DeleteMeetingParticipant200ResponseAllOfDataBuilder> {
  /// Timestamp this object was created at. The time is returned in ISO format.
  @BuiltValueField(wireName: r'created_at')
  DateTime get createdAt;

  /// A unique participant ID generated by the client.
  @BuiltValueField(wireName: r'custom_participant_id')
  String get customParticipantId;

  /// ID of the preset applied to this participant.
  @BuiltValueField(wireName: r'preset_id')
  String get presetId;

  /// Timestamp this object was updated at. The time is returned in ISO format.
  @BuiltValueField(wireName: r'updated_at')
  DateTime get updatedAt;

  DeleteMeetingParticipant200ResponseAllOfData._();

  factory DeleteMeetingParticipant200ResponseAllOfData([void updates(DeleteMeetingParticipant200ResponseAllOfDataBuilder b)]) = _$DeleteMeetingParticipant200ResponseAllOfData;

  @BuiltValueHook(initializeBuilder: true)
  static void _defaults(DeleteMeetingParticipant200ResponseAllOfDataBuilder b) => b;

  @BuiltValueSerializer(custom: true)
  static Serializer<DeleteMeetingParticipant200ResponseAllOfData> get serializer => _$DeleteMeetingParticipant200ResponseAllOfDataSerializer();
}

class _$DeleteMeetingParticipant200ResponseAllOfDataSerializer implements PrimitiveSerializer<DeleteMeetingParticipant200ResponseAllOfData> {
  @override
  final Iterable<Type> types = const [DeleteMeetingParticipant200ResponseAllOfData, _$DeleteMeetingParticipant200ResponseAllOfData];

  @override
  final String wireName = r'DeleteMeetingParticipant200ResponseAllOfData';

  Iterable<Object?> _serializeProperties(
    Serializers serializers,
    DeleteMeetingParticipant200ResponseAllOfData object, {
    FullType specifiedType = FullType.unspecified,
  }) sync* {
    yield r'created_at';
    yield serializers.serialize(
      object.createdAt,
      specifiedType: const FullType(DateTime),
    );
    yield r'custom_participant_id';
    yield serializers.serialize(
      object.customParticipantId,
      specifiedType: const FullType(String),
    );
    yield r'preset_id';
    yield serializers.serialize(
      object.presetId,
      specifiedType: const FullType(String),
    );
    yield r'updated_at';
    yield serializers.serialize(
      object.updatedAt,
      specifiedType: const FullType(DateTime),
    );
  }

  @override
  Object serialize(
    Serializers serializers,
    DeleteMeetingParticipant200ResponseAllOfData object, {
    FullType specifiedType = FullType.unspecified,
  }) {
    return _serializeProperties(serializers, object, specifiedType: specifiedType).toList();
  }

  void _deserializeProperties(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
    required List<Object?> serializedList,
    required DeleteMeetingParticipant200ResponseAllOfDataBuilder result,
    required List<Object?> unhandled,
  }) {
    for (var i = 0; i < serializedList.length; i += 2) {
      final key = serializedList[i] as String;
      final value = serializedList[i + 1];
      switch (key) {
        case r'created_at':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(DateTime),
          ) as DateTime;
          result.createdAt = valueDes;
          break;
        case r'custom_participant_id':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(String),
          ) as String;
          result.customParticipantId = valueDes;
          break;
        case r'preset_id':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(String),
          ) as String;
          result.presetId = valueDes;
          break;
        case r'updated_at':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(DateTime),
          ) as DateTime;
          result.updatedAt = valueDes;
          break;
        default:
          unhandled.add(key);
          unhandled.add(value);
          break;
      }
    }
  }

  @override
  DeleteMeetingParticipant200ResponseAllOfData deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final result = DeleteMeetingParticipant200ResponseAllOfDataBuilder();
    final serializedList = (serialized as Iterable<Object?>).toList();
    final unhandled = <Object?>[];
    _deserializeProperties(
      serializers,
      serialized,
      specifiedType: specifiedType,
      serializedList: serializedList,
      unhandled: unhandled,
      result: result,
    );
    return result.build();
  }
}

