//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:cloudflare_dart/src/model/dnssec_status.dart';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'dnssec_dnssec.g.dart';

/// DnssecDnssec
///
/// Properties:
/// * [algorithm] - Algorithm key code.
/// * [digest] - Digest hash.
/// * [digestAlgorithm] - Type of digest algorithm.
/// * [digestType] - Coded type for digest algorithm.
/// * [dnssecMultiSigner] - If true, multi-signer DNSSEC is enabled on the zone, allowing multiple providers to serve a DNSSEC-signed zone at the same time. This is required for DNSKEY records (except those automatically generated by Cloudflare) to be added to the zone.  See [Multi-signer DNSSEC](https://developers.cloudflare.com/dns/dnssec/multi-signer-dnssec/) for details.
/// * [dnssecPresigned] - If true, allows Cloudflare to transfer in a DNSSEC-signed zone including signatures from an external provider, without requiring Cloudflare to sign any records on the fly.  Note that this feature has some limitations. See [Cloudflare as Secondary](https://developers.cloudflare.com/dns/zone-setups/zone-transfers/cloudflare-as-secondary/setup/#dnssec) for details.
/// * [dnssecUseNsec3] - If true, enables the use of NSEC3 together with DNSSEC on the zone. Combined with setting dnssec_presigned to true, this enables the use of NSEC3 records when transferring in from an external provider. If dnssec_presigned is instead set to false (default), NSEC3 records will be generated and signed at request time.  See [DNSSEC with NSEC3](https://developers.cloudflare.com/dns/dnssec/enable-nsec3/) for details.
/// * [ds] - Full DS record.
/// * [flags] - Flag for DNSSEC record.
/// * [keyTag] - Code for key tag.
/// * [keyType] - Algorithm key type.
/// * [modifiedOn] - When DNSSEC was last modified.
/// * [publicKey] - Public key for DS record.
/// * [status] 
@BuiltValue()
abstract class DnssecDnssec implements Built<DnssecDnssec, DnssecDnssecBuilder> {
  /// Algorithm key code.
  @BuiltValueField(wireName: r'algorithm')
  String? get algorithm;

  /// Digest hash.
  @BuiltValueField(wireName: r'digest')
  String? get digest;

  /// Type of digest algorithm.
  @BuiltValueField(wireName: r'digest_algorithm')
  String? get digestAlgorithm;

  /// Coded type for digest algorithm.
  @BuiltValueField(wireName: r'digest_type')
  String? get digestType;

  /// If true, multi-signer DNSSEC is enabled on the zone, allowing multiple providers to serve a DNSSEC-signed zone at the same time. This is required for DNSKEY records (except those automatically generated by Cloudflare) to be added to the zone.  See [Multi-signer DNSSEC](https://developers.cloudflare.com/dns/dnssec/multi-signer-dnssec/) for details.
  @BuiltValueField(wireName: r'dnssec_multi_signer')
  bool? get dnssecMultiSigner;

  /// If true, allows Cloudflare to transfer in a DNSSEC-signed zone including signatures from an external provider, without requiring Cloudflare to sign any records on the fly.  Note that this feature has some limitations. See [Cloudflare as Secondary](https://developers.cloudflare.com/dns/zone-setups/zone-transfers/cloudflare-as-secondary/setup/#dnssec) for details.
  @BuiltValueField(wireName: r'dnssec_presigned')
  bool? get dnssecPresigned;

  /// If true, enables the use of NSEC3 together with DNSSEC on the zone. Combined with setting dnssec_presigned to true, this enables the use of NSEC3 records when transferring in from an external provider. If dnssec_presigned is instead set to false (default), NSEC3 records will be generated and signed at request time.  See [DNSSEC with NSEC3](https://developers.cloudflare.com/dns/dnssec/enable-nsec3/) for details.
  @BuiltValueField(wireName: r'dnssec_use_nsec3')
  bool? get dnssecUseNsec3;

  /// Full DS record.
  @BuiltValueField(wireName: r'ds')
  String? get ds;

  /// Flag for DNSSEC record.
  @BuiltValueField(wireName: r'flags')
  num? get flags;

  /// Code for key tag.
  @BuiltValueField(wireName: r'key_tag')
  num? get keyTag;

  /// Algorithm key type.
  @BuiltValueField(wireName: r'key_type')
  String? get keyType;

  /// When DNSSEC was last modified.
  @BuiltValueField(wireName: r'modified_on')
  DateTime? get modifiedOn;

  /// Public key for DS record.
  @BuiltValueField(wireName: r'public_key')
  String? get publicKey;

  @BuiltValueField(wireName: r'status')
  DnssecStatus? get status;
  // enum statusEnum {  active,  pending,  disabled,  pending-disabled,  error,  };

  DnssecDnssec._();

  factory DnssecDnssec([void updates(DnssecDnssecBuilder b)]) = _$DnssecDnssec;

  @BuiltValueHook(initializeBuilder: true)
  static void _defaults(DnssecDnssecBuilder b) => b;

  @BuiltValueSerializer(custom: true)
  static Serializer<DnssecDnssec> get serializer => _$DnssecDnssecSerializer();
}

class _$DnssecDnssecSerializer implements PrimitiveSerializer<DnssecDnssec> {
  @override
  final Iterable<Type> types = const [DnssecDnssec, _$DnssecDnssec];

  @override
  final String wireName = r'DnssecDnssec';

  Iterable<Object?> _serializeProperties(
    Serializers serializers,
    DnssecDnssec object, {
    FullType specifiedType = FullType.unspecified,
  }) sync* {
    if (object.algorithm != null) {
      yield r'algorithm';
      yield serializers.serialize(
        object.algorithm,
        specifiedType: const FullType.nullable(String),
      );
    }
    if (object.digest != null) {
      yield r'digest';
      yield serializers.serialize(
        object.digest,
        specifiedType: const FullType.nullable(String),
      );
    }
    if (object.digestAlgorithm != null) {
      yield r'digest_algorithm';
      yield serializers.serialize(
        object.digestAlgorithm,
        specifiedType: const FullType.nullable(String),
      );
    }
    if (object.digestType != null) {
      yield r'digest_type';
      yield serializers.serialize(
        object.digestType,
        specifiedType: const FullType.nullable(String),
      );
    }
    if (object.dnssecMultiSigner != null) {
      yield r'dnssec_multi_signer';
      yield serializers.serialize(
        object.dnssecMultiSigner,
        specifiedType: const FullType(bool),
      );
    }
    if (object.dnssecPresigned != null) {
      yield r'dnssec_presigned';
      yield serializers.serialize(
        object.dnssecPresigned,
        specifiedType: const FullType(bool),
      );
    }
    if (object.dnssecUseNsec3 != null) {
      yield r'dnssec_use_nsec3';
      yield serializers.serialize(
        object.dnssecUseNsec3,
        specifiedType: const FullType(bool),
      );
    }
    if (object.ds != null) {
      yield r'ds';
      yield serializers.serialize(
        object.ds,
        specifiedType: const FullType.nullable(String),
      );
    }
    if (object.flags != null) {
      yield r'flags';
      yield serializers.serialize(
        object.flags,
        specifiedType: const FullType.nullable(num),
      );
    }
    if (object.keyTag != null) {
      yield r'key_tag';
      yield serializers.serialize(
        object.keyTag,
        specifiedType: const FullType.nullable(num),
      );
    }
    if (object.keyType != null) {
      yield r'key_type';
      yield serializers.serialize(
        object.keyType,
        specifiedType: const FullType.nullable(String),
      );
    }
    if (object.modifiedOn != null) {
      yield r'modified_on';
      yield serializers.serialize(
        object.modifiedOn,
        specifiedType: const FullType.nullable(DateTime),
      );
    }
    if (object.publicKey != null) {
      yield r'public_key';
      yield serializers.serialize(
        object.publicKey,
        specifiedType: const FullType.nullable(String),
      );
    }
    if (object.status != null) {
      yield r'status';
      yield serializers.serialize(
        object.status,
        specifiedType: const FullType(DnssecStatus),
      );
    }
  }

  @override
  Object serialize(
    Serializers serializers,
    DnssecDnssec object, {
    FullType specifiedType = FullType.unspecified,
  }) {
    return _serializeProperties(serializers, object, specifiedType: specifiedType).toList();
  }

  void _deserializeProperties(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
    required List<Object?> serializedList,
    required DnssecDnssecBuilder result,
    required List<Object?> unhandled,
  }) {
    for (var i = 0; i < serializedList.length; i += 2) {
      final key = serializedList[i] as String;
      final value = serializedList[i + 1];
      switch (key) {
        case r'algorithm':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.algorithm = valueDes;
          break;
        case r'digest':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.digest = valueDes;
          break;
        case r'digest_algorithm':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.digestAlgorithm = valueDes;
          break;
        case r'digest_type':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.digestType = valueDes;
          break;
        case r'dnssec_multi_signer':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(bool),
          ) as bool;
          result.dnssecMultiSigner = valueDes;
          break;
        case r'dnssec_presigned':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(bool),
          ) as bool;
          result.dnssecPresigned = valueDes;
          break;
        case r'dnssec_use_nsec3':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(bool),
          ) as bool;
          result.dnssecUseNsec3 = valueDes;
          break;
        case r'ds':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.ds = valueDes;
          break;
        case r'flags':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(num),
          ) as num?;
          if (valueDes == null) continue;
          result.flags = valueDes;
          break;
        case r'key_tag':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(num),
          ) as num?;
          if (valueDes == null) continue;
          result.keyTag = valueDes;
          break;
        case r'key_type':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.keyType = valueDes;
          break;
        case r'modified_on':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(DateTime),
          ) as DateTime?;
          if (valueDes == null) continue;
          result.modifiedOn = valueDes;
          break;
        case r'public_key':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.publicKey = valueDes;
          break;
        case r'status':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(DnssecStatus),
          ) as DnssecStatus;
          result.status = valueDes;
          break;
        default:
          unhandled.add(key);
          unhandled.add(value);
          break;
      }
    }
  }

  @override
  DnssecDnssec deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final result = DnssecDnssecBuilder();
    final serializedList = (serialized as Iterable<Object?>).toList();
    final unhandled = <Object?>[];
    _deserializeProperties(
      serializers,
      serialized,
      specifiedType: specifiedType,
      serializedList: serializedList,
      unhandled: unhandled,
      result: result,
    );
    return result.build();
  }
}

