//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:built_collection/built_collection.dart';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'dnssec_edit_dnssec_status_request.g.dart';

/// DnssecEditDnssecStatusRequest
///
/// Properties:
/// * [dnssecMultiSigner] - If true, multi-signer DNSSEC is enabled on the zone, allowing multiple providers to serve a DNSSEC-signed zone at the same time. This is required for DNSKEY records (except those automatically generated by Cloudflare) to be added to the zone.  See [Multi-signer DNSSEC](https://developers.cloudflare.com/dns/dnssec/multi-signer-dnssec/) for details.
/// * [dnssecPresigned] - If true, allows Cloudflare to transfer in a DNSSEC-signed zone including signatures from an external provider, without requiring Cloudflare to sign any records on the fly.  Note that this feature has some limitations. See [Cloudflare as Secondary](https://developers.cloudflare.com/dns/zone-setups/zone-transfers/cloudflare-as-secondary/setup/#dnssec) for details.
/// * [dnssecUseNsec3] - If true, enables the use of NSEC3 together with DNSSEC on the zone. Combined with setting dnssec_presigned to true, this enables the use of NSEC3 records when transferring in from an external provider. If dnssec_presigned is instead set to false (default), NSEC3 records will be generated and signed at request time.  See [DNSSEC with NSEC3](https://developers.cloudflare.com/dns/dnssec/enable-nsec3/) for details.
/// * [status] - Status of DNSSEC, based on user-desired state and presence of necessary records.
@BuiltValue()
abstract class DnssecEditDnssecStatusRequest implements Built<DnssecEditDnssecStatusRequest, DnssecEditDnssecStatusRequestBuilder> {
  /// If true, multi-signer DNSSEC is enabled on the zone, allowing multiple providers to serve a DNSSEC-signed zone at the same time. This is required for DNSKEY records (except those automatically generated by Cloudflare) to be added to the zone.  See [Multi-signer DNSSEC](https://developers.cloudflare.com/dns/dnssec/multi-signer-dnssec/) for details.
  @BuiltValueField(wireName: r'dnssec_multi_signer')
  bool? get dnssecMultiSigner;

  /// If true, allows Cloudflare to transfer in a DNSSEC-signed zone including signatures from an external provider, without requiring Cloudflare to sign any records on the fly.  Note that this feature has some limitations. See [Cloudflare as Secondary](https://developers.cloudflare.com/dns/zone-setups/zone-transfers/cloudflare-as-secondary/setup/#dnssec) for details.
  @BuiltValueField(wireName: r'dnssec_presigned')
  bool? get dnssecPresigned;

  /// If true, enables the use of NSEC3 together with DNSSEC on the zone. Combined with setting dnssec_presigned to true, this enables the use of NSEC3 records when transferring in from an external provider. If dnssec_presigned is instead set to false (default), NSEC3 records will be generated and signed at request time.  See [DNSSEC with NSEC3](https://developers.cloudflare.com/dns/dnssec/enable-nsec3/) for details.
  @BuiltValueField(wireName: r'dnssec_use_nsec3')
  bool? get dnssecUseNsec3;

  /// Status of DNSSEC, based on user-desired state and presence of necessary records.
  @BuiltValueField(wireName: r'status')
  DnssecEditDnssecStatusRequestStatusEnum? get status;
  // enum statusEnum {  active,  disabled,  };

  DnssecEditDnssecStatusRequest._();

  factory DnssecEditDnssecStatusRequest([void updates(DnssecEditDnssecStatusRequestBuilder b)]) = _$DnssecEditDnssecStatusRequest;

  @BuiltValueHook(initializeBuilder: true)
  static void _defaults(DnssecEditDnssecStatusRequestBuilder b) => b;

  @BuiltValueSerializer(custom: true)
  static Serializer<DnssecEditDnssecStatusRequest> get serializer => _$DnssecEditDnssecStatusRequestSerializer();
}

class _$DnssecEditDnssecStatusRequestSerializer implements PrimitiveSerializer<DnssecEditDnssecStatusRequest> {
  @override
  final Iterable<Type> types = const [DnssecEditDnssecStatusRequest, _$DnssecEditDnssecStatusRequest];

  @override
  final String wireName = r'DnssecEditDnssecStatusRequest';

  Iterable<Object?> _serializeProperties(
    Serializers serializers,
    DnssecEditDnssecStatusRequest object, {
    FullType specifiedType = FullType.unspecified,
  }) sync* {
    if (object.dnssecMultiSigner != null) {
      yield r'dnssec_multi_signer';
      yield serializers.serialize(
        object.dnssecMultiSigner,
        specifiedType: const FullType(bool),
      );
    }
    if (object.dnssecPresigned != null) {
      yield r'dnssec_presigned';
      yield serializers.serialize(
        object.dnssecPresigned,
        specifiedType: const FullType(bool),
      );
    }
    if (object.dnssecUseNsec3 != null) {
      yield r'dnssec_use_nsec3';
      yield serializers.serialize(
        object.dnssecUseNsec3,
        specifiedType: const FullType(bool),
      );
    }
    if (object.status != null) {
      yield r'status';
      yield serializers.serialize(
        object.status,
        specifiedType: const FullType(DnssecEditDnssecStatusRequestStatusEnum),
      );
    }
  }

  @override
  Object serialize(
    Serializers serializers,
    DnssecEditDnssecStatusRequest object, {
    FullType specifiedType = FullType.unspecified,
  }) {
    return _serializeProperties(serializers, object, specifiedType: specifiedType).toList();
  }

  void _deserializeProperties(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
    required List<Object?> serializedList,
    required DnssecEditDnssecStatusRequestBuilder result,
    required List<Object?> unhandled,
  }) {
    for (var i = 0; i < serializedList.length; i += 2) {
      final key = serializedList[i] as String;
      final value = serializedList[i + 1];
      switch (key) {
        case r'dnssec_multi_signer':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(bool),
          ) as bool;
          result.dnssecMultiSigner = valueDes;
          break;
        case r'dnssec_presigned':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(bool),
          ) as bool;
          result.dnssecPresigned = valueDes;
          break;
        case r'dnssec_use_nsec3':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(bool),
          ) as bool;
          result.dnssecUseNsec3 = valueDes;
          break;
        case r'status':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(DnssecEditDnssecStatusRequestStatusEnum),
          ) as DnssecEditDnssecStatusRequestStatusEnum;
          result.status = valueDes;
          break;
        default:
          unhandled.add(key);
          unhandled.add(value);
          break;
      }
    }
  }

  @override
  DnssecEditDnssecStatusRequest deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final result = DnssecEditDnssecStatusRequestBuilder();
    final serializedList = (serialized as Iterable<Object?>).toList();
    final unhandled = <Object?>[];
    _deserializeProperties(
      serializers,
      serialized,
      specifiedType: specifiedType,
      serializedList: serializedList,
      unhandled: unhandled,
      result: result,
    );
    return result.build();
  }
}

class DnssecEditDnssecStatusRequestStatusEnum extends EnumClass {

  /// Status of DNSSEC, based on user-desired state and presence of necessary records.
  @BuiltValueEnumConst(wireName: r'active')
  static const DnssecEditDnssecStatusRequestStatusEnum active = _$dnssecEditDnssecStatusRequestStatusEnum_active;
  /// Status of DNSSEC, based on user-desired state and presence of necessary records.
  @BuiltValueEnumConst(wireName: r'disabled')
  static const DnssecEditDnssecStatusRequestStatusEnum disabled = _$dnssecEditDnssecStatusRequestStatusEnum_disabled;

  static Serializer<DnssecEditDnssecStatusRequestStatusEnum> get serializer => _$dnssecEditDnssecStatusRequestStatusSerializer;

  const DnssecEditDnssecStatusRequestStatusEnum._(String name): super(name);

  static BuiltSet<DnssecEditDnssecStatusRequestStatusEnum> get values => _$dnssecEditDnssecStatusRequestStatusValues;
  static DnssecEditDnssecStatusRequestStatusEnum valueOf(String name) => _$dnssecEditDnssecStatusRequestStatusValueOf(name);
}

