//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:built_collection/built_collection.dart';
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'load_balancing_steering_policy.g.dart';

class LoadBalancingSteeringPolicy extends EnumClass {

  /// Steering Policy for this load balancer. - `\"off\"`: Use `default_pools`. - `\"geo\"`: Use `region_pools`/`country_pools`/`pop_pools`. For non-proxied requests, the country for `country_pools` is determined by `location_strategy`. - `\"random\"`: Select a pool randomly. - `\"dynamic_latency\"`: Use round trip time to select the closest pool in default_pools (requires pool health checks). - `\"proximity\"`: Use the pools' latitude and longitude to select the closest pool using the Cloudflare PoP location for proxied requests or the location determined by `location_strategy` for non-proxied requests. - `\"least_outstanding_requests\"`: Select a pool by taking into consideration `random_steering` weights, as well as each pool's number of outstanding requests. Pools with more pending requests are weighted proportionately less relative to others. - `\"least_connections\"`: Select a pool by taking into consideration `random_steering` weights, as well as each pool's number of open connections. Pools with more open connections are weighted proportionately less relative to others. Supported for HTTP/1 and HTTP/2 connections. - `\"\"`: Will map to `\"geo\"` if you use `region_pools`/`country_pools`/`pop_pools` otherwise `\"off\"`.
  @BuiltValueEnumConst(wireName: r'off')
  static const LoadBalancingSteeringPolicy off = _$off;
  /// Steering Policy for this load balancer. - `\"off\"`: Use `default_pools`. - `\"geo\"`: Use `region_pools`/`country_pools`/`pop_pools`. For non-proxied requests, the country for `country_pools` is determined by `location_strategy`. - `\"random\"`: Select a pool randomly. - `\"dynamic_latency\"`: Use round trip time to select the closest pool in default_pools (requires pool health checks). - `\"proximity\"`: Use the pools' latitude and longitude to select the closest pool using the Cloudflare PoP location for proxied requests or the location determined by `location_strategy` for non-proxied requests. - `\"least_outstanding_requests\"`: Select a pool by taking into consideration `random_steering` weights, as well as each pool's number of outstanding requests. Pools with more pending requests are weighted proportionately less relative to others. - `\"least_connections\"`: Select a pool by taking into consideration `random_steering` weights, as well as each pool's number of open connections. Pools with more open connections are weighted proportionately less relative to others. Supported for HTTP/1 and HTTP/2 connections. - `\"\"`: Will map to `\"geo\"` if you use `region_pools`/`country_pools`/`pop_pools` otherwise `\"off\"`.
  @BuiltValueEnumConst(wireName: r'geo')
  static const LoadBalancingSteeringPolicy geo = _$geo;
  /// Steering Policy for this load balancer. - `\"off\"`: Use `default_pools`. - `\"geo\"`: Use `region_pools`/`country_pools`/`pop_pools`. For non-proxied requests, the country for `country_pools` is determined by `location_strategy`. - `\"random\"`: Select a pool randomly. - `\"dynamic_latency\"`: Use round trip time to select the closest pool in default_pools (requires pool health checks). - `\"proximity\"`: Use the pools' latitude and longitude to select the closest pool using the Cloudflare PoP location for proxied requests or the location determined by `location_strategy` for non-proxied requests. - `\"least_outstanding_requests\"`: Select a pool by taking into consideration `random_steering` weights, as well as each pool's number of outstanding requests. Pools with more pending requests are weighted proportionately less relative to others. - `\"least_connections\"`: Select a pool by taking into consideration `random_steering` weights, as well as each pool's number of open connections. Pools with more open connections are weighted proportionately less relative to others. Supported for HTTP/1 and HTTP/2 connections. - `\"\"`: Will map to `\"geo\"` if you use `region_pools`/`country_pools`/`pop_pools` otherwise `\"off\"`.
  @BuiltValueEnumConst(wireName: r'random')
  static const LoadBalancingSteeringPolicy random = _$random;
  /// Steering Policy for this load balancer. - `\"off\"`: Use `default_pools`. - `\"geo\"`: Use `region_pools`/`country_pools`/`pop_pools`. For non-proxied requests, the country for `country_pools` is determined by `location_strategy`. - `\"random\"`: Select a pool randomly. - `\"dynamic_latency\"`: Use round trip time to select the closest pool in default_pools (requires pool health checks). - `\"proximity\"`: Use the pools' latitude and longitude to select the closest pool using the Cloudflare PoP location for proxied requests or the location determined by `location_strategy` for non-proxied requests. - `\"least_outstanding_requests\"`: Select a pool by taking into consideration `random_steering` weights, as well as each pool's number of outstanding requests. Pools with more pending requests are weighted proportionately less relative to others. - `\"least_connections\"`: Select a pool by taking into consideration `random_steering` weights, as well as each pool's number of open connections. Pools with more open connections are weighted proportionately less relative to others. Supported for HTTP/1 and HTTP/2 connections. - `\"\"`: Will map to `\"geo\"` if you use `region_pools`/`country_pools`/`pop_pools` otherwise `\"off\"`.
  @BuiltValueEnumConst(wireName: r'dynamic_latency')
  static const LoadBalancingSteeringPolicy dynamicLatency = _$dynamicLatency;
  /// Steering Policy for this load balancer. - `\"off\"`: Use `default_pools`. - `\"geo\"`: Use `region_pools`/`country_pools`/`pop_pools`. For non-proxied requests, the country for `country_pools` is determined by `location_strategy`. - `\"random\"`: Select a pool randomly. - `\"dynamic_latency\"`: Use round trip time to select the closest pool in default_pools (requires pool health checks). - `\"proximity\"`: Use the pools' latitude and longitude to select the closest pool using the Cloudflare PoP location for proxied requests or the location determined by `location_strategy` for non-proxied requests. - `\"least_outstanding_requests\"`: Select a pool by taking into consideration `random_steering` weights, as well as each pool's number of outstanding requests. Pools with more pending requests are weighted proportionately less relative to others. - `\"least_connections\"`: Select a pool by taking into consideration `random_steering` weights, as well as each pool's number of open connections. Pools with more open connections are weighted proportionately less relative to others. Supported for HTTP/1 and HTTP/2 connections. - `\"\"`: Will map to `\"geo\"` if you use `region_pools`/`country_pools`/`pop_pools` otherwise `\"off\"`.
  @BuiltValueEnumConst(wireName: r'proximity')
  static const LoadBalancingSteeringPolicy proximity = _$proximity;
  /// Steering Policy for this load balancer. - `\"off\"`: Use `default_pools`. - `\"geo\"`: Use `region_pools`/`country_pools`/`pop_pools`. For non-proxied requests, the country for `country_pools` is determined by `location_strategy`. - `\"random\"`: Select a pool randomly. - `\"dynamic_latency\"`: Use round trip time to select the closest pool in default_pools (requires pool health checks). - `\"proximity\"`: Use the pools' latitude and longitude to select the closest pool using the Cloudflare PoP location for proxied requests or the location determined by `location_strategy` for non-proxied requests. - `\"least_outstanding_requests\"`: Select a pool by taking into consideration `random_steering` weights, as well as each pool's number of outstanding requests. Pools with more pending requests are weighted proportionately less relative to others. - `\"least_connections\"`: Select a pool by taking into consideration `random_steering` weights, as well as each pool's number of open connections. Pools with more open connections are weighted proportionately less relative to others. Supported for HTTP/1 and HTTP/2 connections. - `\"\"`: Will map to `\"geo\"` if you use `region_pools`/`country_pools`/`pop_pools` otherwise `\"off\"`.
  @BuiltValueEnumConst(wireName: r'least_outstanding_requests')
  static const LoadBalancingSteeringPolicy leastOutstandingRequests = _$leastOutstandingRequests;
  /// Steering Policy for this load balancer. - `\"off\"`: Use `default_pools`. - `\"geo\"`: Use `region_pools`/`country_pools`/`pop_pools`. For non-proxied requests, the country for `country_pools` is determined by `location_strategy`. - `\"random\"`: Select a pool randomly. - `\"dynamic_latency\"`: Use round trip time to select the closest pool in default_pools (requires pool health checks). - `\"proximity\"`: Use the pools' latitude and longitude to select the closest pool using the Cloudflare PoP location for proxied requests or the location determined by `location_strategy` for non-proxied requests. - `\"least_outstanding_requests\"`: Select a pool by taking into consideration `random_steering` weights, as well as each pool's number of outstanding requests. Pools with more pending requests are weighted proportionately less relative to others. - `\"least_connections\"`: Select a pool by taking into consideration `random_steering` weights, as well as each pool's number of open connections. Pools with more open connections are weighted proportionately less relative to others. Supported for HTTP/1 and HTTP/2 connections. - `\"\"`: Will map to `\"geo\"` if you use `region_pools`/`country_pools`/`pop_pools` otherwise `\"off\"`.
  @BuiltValueEnumConst(wireName: r'least_connections')
  static const LoadBalancingSteeringPolicy leastConnections = _$leastConnections;
  /// Steering Policy for this load balancer. - `\"off\"`: Use `default_pools`. - `\"geo\"`: Use `region_pools`/`country_pools`/`pop_pools`. For non-proxied requests, the country for `country_pools` is determined by `location_strategy`. - `\"random\"`: Select a pool randomly. - `\"dynamic_latency\"`: Use round trip time to select the closest pool in default_pools (requires pool health checks). - `\"proximity\"`: Use the pools' latitude and longitude to select the closest pool using the Cloudflare PoP location for proxied requests or the location determined by `location_strategy` for non-proxied requests. - `\"least_outstanding_requests\"`: Select a pool by taking into consideration `random_steering` weights, as well as each pool's number of outstanding requests. Pools with more pending requests are weighted proportionately less relative to others. - `\"least_connections\"`: Select a pool by taking into consideration `random_steering` weights, as well as each pool's number of open connections. Pools with more open connections are weighted proportionately less relative to others. Supported for HTTP/1 and HTTP/2 connections. - `\"\"`: Will map to `\"geo\"` if you use `region_pools`/`country_pools`/`pop_pools` otherwise `\"off\"`.
  @BuiltValueEnumConst(wireName: r'')
  static const LoadBalancingSteeringPolicy empty = _$empty;

  static Serializer<LoadBalancingSteeringPolicy> get serializer => _$loadBalancingSteeringPolicySerializer;

  const LoadBalancingSteeringPolicy._(String name): super(name);

  static BuiltSet<LoadBalancingSteeringPolicy> get values => _$values;
  static LoadBalancingSteeringPolicy valueOf(String name) => _$valueOf(name);
}

/// Optionally, enum_class can generate a mixin to go with your enum for use
/// with Angular. It exposes your enum constants as getters. So, if you mix it
/// in to your Dart component class, the values become available to the
/// corresponding Angular template.
///
/// Trigger mixin generation by writing a line like this one next to your enum.
abstract class LoadBalancingSteeringPolicyMixin = Object with _$LoadBalancingSteeringPolicyMixin;

