//
// AUTO-GENERATED FILE, DO NOT MODIFY!
//

// ignore_for_file: unused_element
import 'package:built_value/built_value.dart';
import 'package:built_value/serializer.dart';

part 'realtimekit_participant.g.dart';

/// Represents a participant.
///
/// Properties:
/// * [createdAt] - When this object was created. The time is returned in ISO format.
/// * [customParticipantId] - A unique participant ID generated by the client.
/// * [id] - ID of the participant.
/// * [presetName] - Preset applied to the participant.
/// * [updatedAt] - When this object was updated. The time is returned in ISO format.
/// * [name] - Name of the participant.
/// * [picture] - URL to a picture of the participant.
@BuiltValue(instantiable: false)
abstract class RealtimekitParticipant  {
  /// When this object was created. The time is returned in ISO format.
  @BuiltValueField(wireName: r'created_at')
  DateTime get createdAt;

  /// A unique participant ID generated by the client.
  @BuiltValueField(wireName: r'custom_participant_id')
  String get customParticipantId;

  /// ID of the participant.
  @BuiltValueField(wireName: r'id')
  String get id;

  /// Preset applied to the participant.
  @BuiltValueField(wireName: r'preset_name')
  String get presetName;

  /// When this object was updated. The time is returned in ISO format.
  @BuiltValueField(wireName: r'updated_at')
  DateTime get updatedAt;

  /// Name of the participant.
  @BuiltValueField(wireName: r'name')
  String? get name;

  /// URL to a picture of the participant.
  @BuiltValueField(wireName: r'picture')
  String? get picture;

  @BuiltValueSerializer(custom: true)
  static Serializer<RealtimekitParticipant> get serializer => _$RealtimekitParticipantSerializer();
}

class _$RealtimekitParticipantSerializer implements PrimitiveSerializer<RealtimekitParticipant> {
  @override
  final Iterable<Type> types = const [RealtimekitParticipant];

  @override
  final String wireName = r'RealtimekitParticipant';

  Iterable<Object?> _serializeProperties(
    Serializers serializers,
    RealtimekitParticipant object, {
    FullType specifiedType = FullType.unspecified,
  }) sync* {
    yield r'created_at';
    yield serializers.serialize(
      object.createdAt,
      specifiedType: const FullType(DateTime),
    );
    yield r'custom_participant_id';
    yield serializers.serialize(
      object.customParticipantId,
      specifiedType: const FullType(String),
    );
    yield r'id';
    yield serializers.serialize(
      object.id,
      specifiedType: const FullType(String),
    );
    yield r'preset_name';
    yield serializers.serialize(
      object.presetName,
      specifiedType: const FullType(String),
    );
    yield r'updated_at';
    yield serializers.serialize(
      object.updatedAt,
      specifiedType: const FullType(DateTime),
    );
    if (object.name != null) {
      yield r'name';
      yield serializers.serialize(
        object.name,
        specifiedType: const FullType.nullable(String),
      );
    }
    if (object.picture != null) {
      yield r'picture';
      yield serializers.serialize(
        object.picture,
        specifiedType: const FullType.nullable(String),
      );
    }
  }

  @override
  Object serialize(
    Serializers serializers,
    RealtimekitParticipant object, {
    FullType specifiedType = FullType.unspecified,
  }) {
    return _serializeProperties(serializers, object, specifiedType: specifiedType).toList();
  }

  @override
  RealtimekitParticipant deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    return serializers.deserialize(serialized, specifiedType: FullType($RealtimekitParticipant)) as $RealtimekitParticipant;
  }
}

/// a concrete implementation of [RealtimekitParticipant], since [RealtimekitParticipant] is not instantiable
@BuiltValue(instantiable: true)
abstract class $RealtimekitParticipant implements RealtimekitParticipant, Built<$RealtimekitParticipant, $RealtimekitParticipantBuilder> {
  $RealtimekitParticipant._();

  factory $RealtimekitParticipant([void Function($RealtimekitParticipantBuilder)? updates]) = _$$RealtimekitParticipant;

  @BuiltValueHook(initializeBuilder: true)
  static void _defaults($RealtimekitParticipantBuilder b) => b;

  @BuiltValueSerializer(custom: true)
  static Serializer<$RealtimekitParticipant> get serializer => _$$RealtimekitParticipantSerializer();
}

class _$$RealtimekitParticipantSerializer implements PrimitiveSerializer<$RealtimekitParticipant> {
  @override
  final Iterable<Type> types = const [$RealtimekitParticipant, _$$RealtimekitParticipant];

  @override
  final String wireName = r'$RealtimekitParticipant';

  @override
  Object serialize(
    Serializers serializers,
    $RealtimekitParticipant object, {
    FullType specifiedType = FullType.unspecified,
  }) {
    return serializers.serialize(object, specifiedType: FullType(RealtimekitParticipant))!;
  }

  void _deserializeProperties(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
    required List<Object?> serializedList,
    required RealtimekitParticipantBuilder result,
    required List<Object?> unhandled,
  }) {
    for (var i = 0; i < serializedList.length; i += 2) {
      final key = serializedList[i] as String;
      final value = serializedList[i + 1];
      switch (key) {
        case r'created_at':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(DateTime),
          ) as DateTime;
          result.createdAt = valueDes;
          break;
        case r'custom_participant_id':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(String),
          ) as String;
          result.customParticipantId = valueDes;
          break;
        case r'id':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(String),
          ) as String;
          result.id = valueDes;
          break;
        case r'preset_name':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(String),
          ) as String;
          result.presetName = valueDes;
          break;
        case r'updated_at':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType(DateTime),
          ) as DateTime;
          result.updatedAt = valueDes;
          break;
        case r'name':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.name = valueDes;
          break;
        case r'picture':
          final valueDes = serializers.deserialize(
            value,
            specifiedType: const FullType.nullable(String),
          ) as String?;
          if (valueDes == null) continue;
          result.picture = valueDes;
          break;
        default:
          unhandled.add(key);
          unhandled.add(value);
          break;
      }
    }
  }

  @override
  $RealtimekitParticipant deserialize(
    Serializers serializers,
    Object serialized, {
    FullType specifiedType = FullType.unspecified,
  }) {
    final result = $RealtimekitParticipantBuilder();
    final serializedList = (serialized as Iterable<Object?>).toList();
    final unhandled = <Object?>[];
    _deserializeProperties(
      serializers,
      serialized,
      specifiedType: specifiedType,
      serializedList: serializedList,
      unhandled: unhandled,
      result: result,
    );
    return result.build();
  }
}

